"""The effect vocabulary.

Every ``E_*`` parameter name here was verified against the xLights 2026.15
binary rather than harvested from the existing sequences in this show folder --
one of those files has an ``On`` effect whose ``ref`` points at a ``Bars``
settings string, so harvesting would have propagated that corruption.

Two properties keep this safe:

* xLights fills in defaults for any setting we omit, so a partial settings
  string always renders.  We only emit parameters we actually mean.
* xLights ignores settings it does not recognise.  The one thing that must be
  right is the effect's display ``name``, which is why EFFECT_NAMES is closed.

``T_*`` keys are layer/timing settings shared by every effect; ``B_*`` are
render-buffer settings.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path

_REGISTRY_PATH = Path(__file__).resolve().parent.parent / "effect_registry.json"


def _load_registry() -> dict[str, dict]:
    """Effect definitions extracted from the installed xLights app bundle.

    Generated by ``build_registry.py`` from xLights' own effect metadata, so the
    vocabulary is whatever the installed version actually supports rather than a
    hand-kept subset. Re-run that script after upgrading xLights.
    """
    try:
        return json.loads(_REGISTRY_PATH.read_text())["effects"]
    except (OSError, ValueError, KeyError):
        # Without the registry only the curated builders below work; they carry
        # their own verified parameter names, so this degrades rather than dies.
        return {}


REGISTRY = _load_registry()

#: Effect display names, exactly as xLights writes them in the `name` attribute.
#: Only these may be emitted.
EFFECT_NAMES = frozenset(REGISTRY) or frozenset({
    "On", "Bars", "Color Wash", "Spirals", "Butterfly", "Pinwheel",
    "Ripple", "Shockwave", "Twinkle", "Fan", "Galaxy", "Meteors",
})


@dataclass(frozen=True)
class EffectSpec:
    """One effect instance: its display name plus its settings."""

    name: str
    settings: dict[str, str] = field(default_factory=dict)

    def __post_init__(self):
        if self.name not in EFFECT_NAMES:
            raise ValueError(
                f"Unknown xLights effect {self.name!r}. Known: {sorted(EFFECT_NAMES)}"
            )

    def serialize(self) -> str:
        return ",".join(f"{k}={self.settings[k]}" for k in sorted(self.settings))


def _format(info: dict, value) -> str:
    """Render one parameter value the way xLights stores it."""
    ty = info.get("type")

    if ty == "bool":
        return "1" if value else "0"

    if ty == "enum":
        options = info.get("options") or []
        if options and value not in options:
            raise ValueError(
                f"{info['key']}: {value!r} is not one of {options}"
            )
        return str(value)

    if ty in ("int", "float"):
        lo, hi = info.get("min"), info.get("max")
        # A few entries carry a range that contradicts their own default --
        # Wave_Number_Waves defaults to 2.5 with a stated range of [180, 3600].
        # Where the metadata disagrees with itself, clamping would turn a
        # sensible value into a wrong one, so leave it alone.
        default = info.get("default")
        trustworthy = not (
            isinstance(default, (int, float)) and not isinstance(default, bool)
            and ((lo is not None and default < lo)
                 or (hi is not None and default > hi))
        )
        if trustworthy:
            if lo is not None:
                value = max(lo, value)
            if hi is not None:
                value = min(hi, value)
        # A float slider is stored through a text control, so it keeps decimals;
        # an int slider is stored as a plain integer.
        if ty == "float" or info.get("divisor"):
            return f"{float(value):.2f}"
        return str(int(round(value)))

    return str(value)


def build(name: str, *, fade_in: float = 0.0, fade_out: float = 0.0,
          buffer_style: str | None = None, **params) -> EffectSpec:
    """Build any effect the installed xLights supports, by name.

    Parameters are given by their metadata id (``Plasma_Style``, ``Warp_Type``)
    and are checked against the registry: unknown names raise, numbers are
    clamped to the effect's own range, and enum values must be one of the
    options xLights offers. That check is the point -- xLights silently ignores
    settings it does not recognise, so a typo would otherwise show up only as an
    effect mysteriously rendering with defaults.

    The curated builders below stay as the convenient path for the effects used
    most; this covers everything else.
    """
    if name not in REGISTRY:
        raise ValueError(
            f"Unknown xLights effect {name!r}. "
            f"Run build_registry.py if you have upgraded xLights."
        )
    spec = REGISTRY[name]["params"]

    settings = _layer(fade_in, fade_out)
    for pid, value in params.items():
        if pid not in spec:
            close = [k for k in spec if pid.lower() in k.lower()]
            raise ValueError(
                f"{name!r} has no parameter {pid!r}."
                + (f" Did you mean {close}?" if close else
                   f" Available: {sorted(spec)[:12]}...")
            )
        settings[spec[pid]["key"]] = _format(spec[pid], value)

    if buffer_style:
        settings["B_CHOICE_BufferStyle"] = buffer_style
    return EffectSpec(name, settings)


def defaults_for(name: str) -> dict[str, object]:
    """Every parameter of an effect with its xLights default. For exploring."""
    return {pid: info.get("default")
            for pid, info in REGISTRY.get(name, {}).get("params", {}).items()}


def with_fade(spec: EffectSpec, *, fade_in: float | None = None,
              fade_out: float | None = None) -> EffectSpec:
    """A copy of `spec` with its layer fades overridden.

    Lets a caller adjust the fade on an already-built effect without every
    builder having to thread the parameter through.
    """
    s = dict(spec.settings)
    if fade_in is not None:
        s["T_TEXTCTRL_Fadein"] = f"{max(0.0, fade_in):.2f}"
    if fade_out is not None:
        s["T_TEXTCTRL_Fadeout"] = f"{max(0.0, fade_out):.2f}"
    return EffectSpec(spec.name, s)


def _layer(fade_in: float = 0.0, fade_out: float = 0.0, **extra: object) -> dict[str, str]:
    """Common T_* layer settings.

    Fades are in seconds and are what make effects feel musical rather than
    switched -- almost every builder below takes them.
    """
    s = {
        "T_CHECKBOX_Canvas": "0",
        "T_CHECKBOX_LayerMorph": "0",
        "T_CHOICE_LayerMethod": "Normal",
        "T_SLIDER_EffectLayerMix": "0",
        "T_TEXTCTRL_Fadein": f"{max(0.0, fade_in):.2f}",
        "T_TEXTCTRL_Fadeout": f"{max(0.0, fade_out):.2f}",
    }
    s.update({k: str(v) for k, v in extra.items()})
    return s


# ---------------------------------------------------------------------------
# Builders.  Each returns an EffectSpec; the arranger composes them.
# ---------------------------------------------------------------------------

def on(brightness: int = 100, *, fade_in: float = 0.0, fade_out: float = 0.0,
       shimmer: bool = False, end_brightness: int | None = None) -> EffectSpec:
    """Flat color. The workhorse for accents, strobes and the DJ par.

    `brightness` ramps to `end_brightness` across the effect if given.
    """
    end = brightness if end_brightness is None else end_brightness
    return EffectSpec("On", {
        "E_TEXTCTRL_Eff_On_Start": str(int(brightness)),
        "E_TEXTCTRL_Eff_On_End": str(int(end)),
        "E_CHECKBOX_On_Shimmer": "1" if shimmer else "0",
        **_layer(fade_in, fade_out),
    })


def bars(count: int = 3, direction: str = "up", cycles: float = 1.0, *,
         gradient: bool = True, three_d: bool = False,
         fade_in: float = 0.0, fade_out: float = 0.0,
         buffer_style: str | None = None) -> EffectSpec:
    """Moving bars. Direction is one of up/down/left/right/expand/compress
    or their 'Alternate *' variants."""
    s = {
        "E_SLIDER_Bars_BarCount": str(int(count)),
        "E_CHOICE_Bars_Direction": direction,
        "E_TEXTCTRL_Bars_Cycles": f"{cycles:.2f}",
        "E_CHECKBOX_Bars_3D": "1" if three_d else "0",
        "E_CHECKBOX_Bars_Highlight": "0",
        "E_CHECKBOX_Bars_Gradient": "1" if gradient else "0",
        **_layer(fade_in, fade_out),
    }
    if buffer_style:
        s["B_CHOICE_BufferStyle"] = buffer_style
    return EffectSpec("Bars", s)


def color_wash(cycles: float = 0.5, *, vfade: bool = False, hfade: bool = False,
               circular: bool = False, shimmer: bool = False,
               fade_in: float = 0.0, fade_out: float = 0.0) -> EffectSpec:
    """Slow full-buffer color sweep. The default 'bed' effect."""
    return EffectSpec("Color Wash", {
        "E_TEXTCTRL_ColorWash_Cycles": f"{cycles:.2f}",
        "E_CHECKBOX_ColorWash_VFade": "1" if vfade else "0",
        "E_CHECKBOX_ColorWash_HFade": "1" if hfade else "0",
        "E_CHECKBOX_ColorWash_CircularPalette": "1" if circular else "0",
        "E_CHECKBOX_ColorWash_Shimmer": "1" if shimmer else "0",
        **_layer(fade_in, fade_out),
    })


def spirals(count: int = 2, movement: float = 5.0, thickness: int = 25,
            rotation: int = 20, *, blend: bool = True, three_d: bool = False,
            fade_in: float = 0.0, fade_out: float = 0.0) -> EffectSpec:
    return EffectSpec("Spirals", {
        "E_SLIDER_Spirals_Count": str(int(count)),
        "E_TEXTCTRL_Spirals_Movement": f"{movement:.1f}",
        "E_SLIDER_Spirals_Thickness": str(int(thickness)),
        "E_SLIDER_Spirals_Rotation": str(int(rotation)),
        "E_CHECKBOX_Spirals_Blend": "1" if blend else "0",
        "E_CHECKBOX_Spirals_3D": "1" if three_d else "0",
        **_layer(fade_in, fade_out),
    })


def butterfly(style: int = 1, chunks: int = 1, skip: int = 2, speed: int = 10,
              direction: str = "Normal", *,
              fade_in: float = 0.0, fade_out: float = 0.0) -> EffectSpec:
    return EffectSpec("Butterfly", {
        "E_SLIDER_Butterfly_Style": str(int(style)),
        "E_SLIDER_Butterfly_Chunks": str(int(chunks)),
        "E_SLIDER_Butterfly_Skip": str(int(skip)),
        "E_SLIDER_Butterfly_Speed": str(int(speed)),
        "E_CHOICE_Butterfly_Direction": direction,
        **_layer(fade_in, fade_out),
    })


def pinwheel(arms: int = 3, speed: int = 10, thickness: int = 40, twist: int = 0,
             arm_size: int = 100, *, rotation: bool = True,
             fade_in: float = 0.0, fade_out: float = 0.0) -> EffectSpec:
    return EffectSpec("Pinwheel", {
        "E_SLIDER_Pinwheel_Arms": str(int(arms)),
        "E_SLIDER_Pinwheel_Speed": str(int(speed)),
        "E_SLIDER_Pinwheel_Thickness": str(int(thickness)),
        "E_SLIDER_Pinwheel_Twist": str(int(twist)),
        "E_SLIDER_Pinwheel_ArmSize": str(int(arm_size)),
        "E_CHECKBOX_Pinwheel_Rotation": "1" if rotation else "0",
        "E_CHOICE_Pinwheel_Style": "New Render Method",
        **_layer(fade_in, fade_out),
    })


def ripple(obj: str = "Circle", thickness: int = 10, cycles: float = 1.0,
           movement: str = "Explode", *,
           fade_in: float = 0.0, fade_out: float = 0.0) -> EffectSpec:
    """Expanding outline. `obj` may be Circle/Square/Triangle/Star/Heart/Tree.

    Triangle is the natural choice for this rig.
    """
    return EffectSpec("Ripple", {
        "E_CHOICE_Ripple_Object_To_Draw": obj,
        "E_CHOICE_Ripple_Movement": movement,
        "E_SLIDER_Ripple_Thickness": str(int(thickness)),
        "E_TEXTCTRL_Ripple_Cycles": f"{cycles:.2f}",
        **_layer(fade_in, fade_out),
    })


def shockwave(start_radius: int = 0, end_radius: int = 100,
              start_width: int = 5, end_width: int = 15, cycles: int = 1,
              accel: int = 0, *, blend_edges: bool = True,
              fade_in: float = 0.0, fade_out: float = 0.0) -> EffectSpec:
    """Ring blasting outward from the centre. The go-to hit for a drop."""
    return EffectSpec("Shockwave", {
        "E_SLIDER_Shockwave_Start_Radius": str(int(start_radius)),
        "E_SLIDER_Shockwave_End_Radius": str(int(end_radius)),
        "E_SLIDER_Shockwave_Start_Width": str(int(start_width)),
        "E_SLIDER_Shockwave_End_Width": str(int(end_width)),
        "E_SLIDER_Shockwave_Cycles": str(int(cycles)),
        "E_SLIDER_Shockwave_Accel": str(int(accel)),
        "E_SLIDER_Shockwave_CenterX": "50",
        "E_SLIDER_Shockwave_CenterY": "50",
        "E_CHECKBOX_Shockwave_Blend_Edges": "1" if blend_edges else "0",
        "E_CHECKBOX_Shockwave_Scale": "1",
        **_layer(fade_in, fade_out),
    })


def twinkle(count: int = 30, steps: int = 20, *, strobe: bool = False,
            rerandom: bool = True, style: str = "Old Render Method",
            fade_in: float = 0.0, fade_out: float = 0.0) -> EffectSpec:
    return EffectSpec("Twinkle", {
        "E_SLIDER_Twinkle_Count": str(int(count)),
        "E_SLIDER_Twinkle_Steps": str(int(steps)),
        "E_CHECKBOX_Twinkle_Strobe": "1" if strobe else "0",
        "E_CHECKBOX_Twinkle_ReRandom": "1" if rerandom else "0",
        "E_CHOICE_Twinkle_Style": style,
        **_layer(fade_in, fade_out),
    })


def fan(blades: int = 3, elements: int = 1, revolutions: int = 720,
        duration: int = 80, start_radius: int = 0, end_radius: int = 100,
        blade_width: int = 50, blade_angle: int = 90, accel: int = 0, *,
        reverse: bool = False, fade_in: float = 0.0, fade_out: float = 0.0) -> EffectSpec:
    return EffectSpec("Fan", {
        "E_SLIDER_Fan_Num_Blades": str(int(blades)),
        "E_SLIDER_Fan_Num_Elements": str(int(elements)),
        "E_SLIDER_Fan_Revolutions": str(int(revolutions)),
        "E_SLIDER_Fan_Duration": str(int(duration)),
        "E_SLIDER_Fan_Start_Radius": str(int(start_radius)),
        "E_SLIDER_Fan_End_Radius": str(int(end_radius)),
        "E_SLIDER_Fan_Blade_Width": str(int(blade_width)),
        "E_SLIDER_Fan_Blade_Angle": str(int(blade_angle)),
        "E_SLIDER_Fan_Element_Width": "100",
        "E_SLIDER_Fan_CenterX": "50",
        "E_SLIDER_Fan_CenterY": "50",
        "E_SLIDER_Fan_Accel": str(int(accel)),
        "E_CHECKBOX_Fan_Reverse": "1" if reverse else "0",
        "E_CHECKBOX_Fan_Blend_Edges": "1",
        "E_CHECKBOX_Fan_Scale": "1",
        **_layer(fade_in, fade_out),
    })


def galaxy(revolutions: int = 1440, duration: int = 80, start_radius: int = 0,
           end_radius: int = 100, start_width: int = 5, end_width: int = 30,
           start_angle: int = 0, accel: int = 0, *, inward: bool = False,
           reverse: bool = False, fade_in: float = 0.0,
           fade_out: float = 0.0) -> EffectSpec:
    return EffectSpec("Galaxy", {
        "E_SLIDER_Galaxy_Revolutions": str(int(revolutions)),
        "E_SLIDER_Galaxy_Duration": str(int(duration)),
        "E_SLIDER_Galaxy_Start_Radius": str(int(start_radius)),
        "E_SLIDER_Galaxy_End_Radius": str(int(end_radius)),
        "E_SLIDER_Galaxy_Start_Width": str(int(start_width)),
        "E_SLIDER_Galaxy_End_Width": str(int(end_width)),
        "E_SLIDER_Galaxy_Start_Angle": str(int(start_angle)),
        "E_SLIDER_Galaxy_CenterX": "50",
        "E_SLIDER_Galaxy_CenterY": "50",
        "E_SLIDER_Galaxy_Accel": str(int(accel)),
        "E_CHECKBOX_Galaxy_Inward": "1" if inward else "0",
        "E_CHECKBOX_Galaxy_Reverse": "1" if reverse else "0",
        "E_CHECKBOX_Galaxy_Blend_Edges": "1",
        "E_CHECKBOX_Galaxy_Scale": "1",
        **_layer(fade_in, fade_out),
    })


def meteors(count: int = 30, length: int = 25, speed: int = 15,
            effect: str = "Down", mtype: str = "Rainbow", swirl: int = 0, *,
            fade_in: float = 0.0, fade_out: float = 0.0) -> EffectSpec:
    return EffectSpec("Meteors", {
        "E_SLIDER_Meteors_Count": str(int(count)),
        "E_SLIDER_Meteors_Length": str(int(length)),
        "E_SLIDER_Meteors_Speed": str(int(speed)),
        "E_SLIDER_Meteors_Swirl_Intensity": str(int(swirl)),
        "E_CHOICE_Meteors_Effect": effect,
        "E_CHOICE_Meteors_Type": mtype,
        "E_CHECKBOX_Meteors_UseMusic": "0",
        **_layer(fade_in, fade_out),
    })
