"""Fixture inventory, read from the xLights show folder.

Nothing here is hardcoded from memory -- the model and group names are parsed out
of ``xlights_rgbeffects.xml`` at runtime.  Rename something in xLights and this
raises instead of silently emitting a sequence full of dead element names.
"""

from __future__ import annotations

import os
import xml.etree.ElementTree as ET
from dataclasses import dataclass, field
from pathlib import Path

#: Points at the xLights show folder -- the one holding
#: ``xlights_rgbeffects.xml`` and ``xlights_networks.xml``.  The code lives in
#: its own repo, so the show can be anywhere.
ENV_VAR = "TRIANGLES_SHOW_DIR"
#: Where the code used to live: <show folder>/<this repo>/.  Still the fallback,
#: so a checkout dropped inside the show folder needs no setup at all.
PARENT_DIR = Path(__file__).resolve().parent.parent.parent
HOW_TO_POINT = f"Point at the xLights show folder with {ENV_VAR}=/path/to/show."

_configured: Path | None = None


def set_show_dir(path: str | Path | None) -> None:
    """Use this folder when the environment does not name one (live.toml)."""
    global _configured
    _configured = Path(path).expanduser() if path else None


def show_dir() -> Path:
    """The xLights show folder: environment, then config, then the parent."""
    if os.environ.get(ENV_VAR):
        return Path(os.environ[ENV_VAR]).expanduser()
    if _configured is not None:
        return _configured
    return PARENT_DIR


def rgb_effects_path() -> Path:
    return show_dir() / "xlights_rgbeffects.xml"


# Group holding the corridor of triangle arches, front to back.
TUNNEL_GROUP = "Tunnel"
# Net groups we sequence against, in the order they appear in the timeline.
NET_GROUPS = ("All Triangles", "Big Triangle", "Small Triangle Nets")


class ShowError(RuntimeError):
    pass


@dataclass
class Show:
    """Everything the arranger needs to know about the physical rig."""

    #: The 24 arch models in physical front-to-back order.  Names are irregular
    #: ("Poly Line-01", then "Poly Line-2" .. "Poly Line-24") so they must be
    #: read from the group, never generated by formatting an integer.
    tunnel_arches: list[str]
    #: Group name covering the whole corridor.
    tunnel: str
    #: Net model groups, coarse to fine.
    net_groups: list[str]
    #: Individual net models.
    nets: list[str]
    #: The DMX par -- effectively a single pixel -- or None if the layout has
    #: none (it was dropped on 2026-08-30).
    dj: str | None
    #: Every model and group name in the show, for validation.
    all_names: set[str] = field(default_factory=set)

    @property
    def elements(self) -> list[str]:
        """Every element this tool writes effects for, in timeline order.

        Groups first (they are what you look at), then the individual arches,
        then the DJ par.
        """
        return [self.tunnel, *self.net_groups, *self.tunnel_arches,
                *([self.dj] if self.dj else [])]


def load_show(rgb_effects: Path | None = None) -> Show:
    path = Path(rgb_effects) if rgb_effects else rgb_effects_path()
    if not path.exists():
        raise ShowError(f"Could not find {path}.\n{HOW_TO_POINT}")

    root = ET.parse(path).getroot()

    models = {m.get("name"): m for m in root.findall("./models/model")}
    groups = {g.get("name"): g for g in root.findall("./modelGroups/modelGroup")}

    if TUNNEL_GROUP not in groups:
        raise ShowError(
            f"No model group named {TUNNEL_GROUP!r} in {path.name}. "
            f"Found groups: {sorted(groups)}"
        )

    # The order of this attribute IS the physical corridor order.  Do not sort.
    arches = [n.strip() for n in groups[TUNNEL_GROUP].get("models", "").split(",")]
    arches = [n for n in arches if n]
    if not arches:
        raise ShowError(f"Model group {TUNNEL_GROUP!r} is empty.")

    missing = [n for n in arches if n not in models]
    if missing:
        raise ShowError(f"{TUNNEL_GROUP!r} references unknown models: {missing}")

    net_groups = [g for g in NET_GROUPS if g in groups]
    if not net_groups:
        raise ShowError(
            f"None of the expected net groups {NET_GROUPS} exist. "
            f"Found groups: {sorted(groups)}"
        )

    nets = sorted(
        (n for n, m in models.items() if m.get("DisplayAs") == "Custom"),
        key=_natural_key,
    )

    dmx = [n for n, m in models.items() if (m.get("DisplayAs") or "").startswith("Dmx")]
    if len(dmx) > 1:
        # Deterministic pick, but say something -- the arranger only drives one.
        dmx.sort()

    return Show(
        tunnel_arches=arches,
        tunnel=TUNNEL_GROUP,
        net_groups=net_groups,
        nets=nets,
        dj=dmx[0] if dmx else None,
        all_names=set(models) | set(groups),
    )


def _natural_key(name: str):
    """Sort 'Net 2' before 'Net 10'."""
    head = name.rstrip("0123456789")
    tail = name[len(head):]
    return (head, int(tail) if tail else 0)


if __name__ == "__main__":
    show = load_show()
    print(f"Tunnel  : {show.tunnel} -> {len(show.tunnel_arches)} arches")
    print(f"          {show.tunnel_arches[0]} ... {show.tunnel_arches[-1]}")
    print(f"Nets    : {', '.join(show.net_groups)}")
    print(f"          {len(show.nets)} models: {', '.join(show.nets)}")
    print(f"DJ      : {show.dj or 'none'}")
